baseurl = "http://nicecarsband.com/"
languageCode = "en-us"
title = "Nice Cars | Rock Duo from Pittsburgh"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Nice Cars"
	description = "A two man rock band from Pittsburgh PA."

	# The path must be relative to the static folder
	favicon = "favicon.ico"
	googleAnalytics = "UA-76525177-1"

	# Navigation
	[params.navigation]
		brand = "Nice Cars"

		[params.navigation.links]
			music     = "Music"
			videos    = "Videos"
			merch	  = "Merch"
			contact   = "Contact"
			# updates   = "Shows"
			latest = "Latest Release"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Rock Duo from Pittsburgh"
		subtitle   = "\"Don’t name it after me- not the boat, not the kids, not the home\""
		buttonText = "Listen Up"


	# Music section
	[params.music]
		headline    = "Find our music at your favorite spots"
		description = "We have been self releasing music since 2014 and have made it available in as many online streaming services as possible."

	# Videos section
	[params.videos]
		headline    = "Check out our videos"
		description = "We shot a music videos for our songs <em>Trouble</em> and <em>Chlorine</em><br /><a href='https://www.youtube.com/channel/UCjee7dBF1_5SGImyQlxvnmw' class='btn'><i class='fa fa-youtube fa-2x wow bounceIn' data-wow-delay='.1s'></i> YouTube Channel</a> for some single take rehearsal videos."


	# Contact section
	[params.contact]
		headline = "Connect with us"
		description = "When we are not in the studio we like to play around town.<br />Find us on Instagram or Facebook to see when we are playing next, or just email us."
		phone = "123-456-6789"
		email = "nicecarsband@gmail.com"

	# Updates section
	[params.updates]
		headline    = "Social media feed"
		description = "By social media I of course mean facebook."

	[params.showsPast]
		headline    = "Recent shows"
		description = "Bright lights, cold beers."

		[[params.showsPast.list]]
			date = "10/06/2018"
			venue = "Club Cage - Pittsburgh / South Side"
			details = "Opening for Jon Worthy & Norm"

		[[params.showsPast.list]]
			date = "1/14/2016"
			venue = "Club Cafe - Pittsburgh / South Side"
			details = "Opening for Shiner"

		[[params.showsPast.list]]
			date = "4/14/2016"
			venue = "Club Cafe - Pittsburgh / South Side"
			details = "Opening for Future Thieves"

		[[params.showsPast.list]]
			date = "5/20/2016"
			venue = "Pinball Perfection - Pittsburgh / West View"
			details = "Rock and Roll Pinball Party with OC Feef"

		[[params.showsPast.list]]
			date = "9/2/2016"
			venue = "Club Cafe - Pittsburgh / South Side"
			details = "Opening for Adelaide in Autum + Cape Cod"

		[[params.showsPast.list]]
			date = "2/26/2017"
			venue = "Club Cafe - Pittsburgh / South Side"
			details = "Opening for Bad Pop"

	[params.showsFuture]
		headline    = "Upcoming shows"
		description = "More dates coming soon."

		[[params.showsFuture.list]]
			date = "6/29/2019"
			venue = "Club Cafe - Pittsburgh / South Side"
			details = "Opening for Jon Worthy and the Bends"
